/**
 * Typed access to the processed images. `imageManifest.json` is generated by
 * `npm run images` (scripts/process-images.mjs); edit sources and alt text there.
 */
import manifest from './imageManifest.json';

export type ImageSlot = keyof typeof manifest;

export interface ImageAsset {
  src: string;
  srcSet: string;
  width: number;
  height: number;
  alt: string;
}

export const images: Record<ImageSlot, ImageAsset> = manifest;
